fix: Concept of the help for keyboard shortcuts TG-297
tolgee/server pull request #792
Opened 2021-09-23 13:25 UTC by stepan662

2021-09-24 09:52 UTC, JanCizmar requested changes
It looks nice, but It doesn't make the process much faster. 

I am still not able to review the translations with hitting single shortcut without moving between translations with mouse or hitting tab many times. I think, that combination of moving with arrows and allowing users to to focus the key items like key or specific translations without opening editor would be the best option. In the focused item or with hover (which can do both the same thing, actually) we can show the shortcuts the way Zuzka designed.

2021-09-24 09:52 UTC, JanCizmar commented on webapp/src/views/projects/translations/ShortcutsHint.tsx
> +  meta?: string;
Maybe we can be more specific here like meta?: 'CTRL' | 'CMD'

2021-09-24 09:52 UTC, JanCizmar commented on webapp/src/views/projects/translations/TranslationOpened.tsx
> +                  name: <T>{translationStates[nextState].translationKey}</T>,
`TypeError: Cannot read properties of undefined (reading 'translationKey')` is thrown when I try to edit untranslated value. Please add test for this.

2021-10-01 13:57 UTC, JanCizmar commented on e2e/cypress/common/shortcuts.ts
> +export const IS_MAC = Boolean(navigator.userAgent.includes('Mac OS X'));
What about older Macs? ❓ 🥇

2021-10-01 14:11 UTC, stepan662 commented on e2e/cypress/common/shortcuts.ts
> +export const IS_MAC = Boolean(navigator.userAgent.includes('Mac OS X'));
Ok, switched to Mac

2021-10-01 14:54 UTC, merged